import 'package:malina_delivery/core/mock_data/product_mock_data_entity.dart';

class ProductMockData {
  static List<ProductMockDataEntity> productsList = [
    // Food products
    ProductMockDataEntity(
      id: 1,
      productId: "f1",
      name: "Том Ям",
      image: "https://s9.stc.all.kpcdn.net/family/wp-content/uploads/2024/02/reczepty-supa-tom-yam-960.jpg",
      price: 250,
      productType: "food",
    ),
    ProductMockDataEntity(
      id: 2,
      productId: "f2",
      name: "Салат Цезарь",
      image: "https://s9.stc.all.kpcdn.net/family/wp-content/uploads/2024/02/reczepty-supa-tom-yam-960.jpg",
      price: 180,
      productType: "food",
    ),
    ProductMockDataEntity(
      id: 3,
      productId: "f3",
      name: "Пицца Маргарита",
      image: "https://s9.stc.all.kpcdn.net/family/wp-content/uploads/2024/02/reczepty-supa-tom-yam-960.jpg",
      price: 320,
      productType: "food",
    ),
    ProductMockDataEntity(
      id: 4,
      productId: "f4",
      name: "Суши Сет",
      image: "https://s9.stc.all.kpcdn.net/family/wp-content/uploads/2024/02/reczepty-supa-tom-yam-960.jpg",
      price: 450,
      productType: "food",
    ),
    ProductMockDataEntity(
      id: 5,
      productId: "f5",
      name: "Роллы Калифорния",
      image: "https://s9.stc.all.kpcdn.net/family/wp-content/uploads/2024/02/reczepty-supa-tom-yam-960.jpg",
      price: 300,
      productType: "food",
    ),
    ProductMockDataEntity(
      id: 6,
      productId: "f6",
      name: "Бургер Классический",
      image: "https://s9.stc.all.kpcdn.net/family/wp-content/uploads/2024/02/reczepty-supa-tom-yam-960.jpg",
      price: 220,
      productType: "food",
    ),
    ProductMockDataEntity(
      id: 7,
      productId: "f7",
      name: "Лапша Удон",
      image: "https://s9.stc.all.kpcdn.net/family/wp-content/uploads/2024/02/reczepty-supa-tom-yam-960.jpg",
      price: 200,
      productType: "food",
    ),
    ProductMockDataEntity(
      id: 8,
      productId: "f8",
      name: "Пельмени",
      image: "https://s9.stc.all.kpcdn.net/family/wp-content/uploads/2024/02/reczepty-supa-tom-yam-960.jpg",
      price: 150,
      productType: "food",
    ),
    ProductMockDataEntity(
      id: 9,
      productId: "f9",
      name: "Борщ",
      image: "https://s9.stc.all.kpcdn.net/family/wp-content/uploads/2024/02/reczepty-supa-tom-yam-960.jpg",
      price: 160,
      productType: "food",
    ),
    ProductMockDataEntity(
      id: 10,
      productId: "f10",
      name: "Плов",
      image: "https://s9.stc.all.kpcdn.net/family/wp-content/uploads/2024/02/reczepty-supa-tom-yam-960.jpg",
      price: 280,
      productType: "food",
    ),

    // Stuff products
    ProductMockDataEntity(
      id: 11,
      productId: "s11",
      name: "Hadat Cosmetics",
      image: "https://m.media-amazon.com/images/I/51RnEZJ82WL.jpg",
      price: 2000,
      productType: "stuff",
    ),
    ProductMockDataEntity(
      id: 12,
      productId: "s12",
      name: "Skincare Essentials",
      image: "https://m.media-amazon.com/images/I/51RnEZJ82WL.jpg",
      price: 1500,
      productType: "stuff",
    ),
    ProductMockDataEntity(
      id: 13,
      productId: "s13",
      name: "Organic Shampoo",
      image: "https://m.media-amazon.com/images/I/51RnEZJ82WL.jpg",
      price: 1200,
      productType: "stuff",
    ),
    ProductMockDataEntity(
      id: 14,
      productId: "s14",
      name: "Natural Conditioner",
      image: "https://m.media-amazon.com/images/I/51RnEZJ82WL.jpg",
      price: 1300,
      productType: "stuff",
    ),
    ProductMockDataEntity(
      id: 15,
      productId: "s15",
      name: "Essential Oils Set",
      image: "https://m.media-amazon.com/images/I/51RnEZJ82WL.jpg",
      price: 2500,
      productType: "stuff",
    ),
    ProductMockDataEntity(
      id: 16,
      productId: "s16",
      name: "Hand Cream",
      image: "https://m.media-amazon.com/images/I/51RnEZJ82WL.jpg",
      price: 800,
      productType: "stuff",
    ),
    ProductMockDataEntity(
      id: 17,
      productId: "s17",
      name: "Body Lotion",
      image: "https://m.media-amazon.com/images/I/51RnEZJ82WL.jpg",
      price: 900,
      productType: "stuff",
    ),
    ProductMockDataEntity(
      id: 18,
      productId: "s18",
      name: "Face Mask Pack",
      image: "https://m.media-amazon.com/images/I/51RnEZJ82WL.jpg",
      price: 1400,
      productType: "stuff",
    ),
    ProductMockDataEntity(
      id: 19,
      productId: "s19",
      name: "Aloe Vera Gel",
      image: "https://m.media-amazon.com/images/I/51RnEZJ82WL.jpg",
      price: 1100,
      productType: "stuff",
    ),
    ProductMockDataEntity(
      id: 20,
      productId: "s20",
      name: "Lip Balm Set",
      image: "https://m.media-amazon.com/images/I/51RnEZJ82WL.jpg",
      price: 600,
      productType: "stuff",
    ),
  ];

}
